#! /bin/sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Zathura state=tiled
bspc config external_rules_command "/home/pantherman594/.config/bspwm/external_rules"

bspc wm -o
bspc wm -O eDP-1 DP-1-1 DP-1-3

num_monitors=$(bspc query -M | wc -l)
init=1
for m in $(bspc query -D -d .active --names); do
  if [ $m != "Desktop" ]; then
    init=0
    break
  fi
done

if [ $init = 1 ]; then
  # subscribe to bspwm events
  ~/.scripts/bspwm_subscriptions.sh &

  # setup initial monitor config
  for (( i=1; i<=$num_monitors; i++ )); do
    bspc monitor ^${i} -d $i
    bspc desktop -f ^${i}:${i}
  done

  #
  # run once
  #

  # set theme
  xrdb ~/.Xresources

  # set autolock after 5 min of inactivity
  xautolock -locker "~/.scripts/lock.sh" -time 5 &

  # start dock daemon
  dockd --daemon &

  # empty trash
  autotrash -d 30 &

  nm-applet &

  xdotool key super+Return; sleep 3; xdotool type "~/.scripts/toggle_redshift.sh &"; xdotool key Return; sleep 1; xdotool key super+shift+q
  export _JAVA_AWT_WM_NONREPARENTING=1

  # bash -c "[[ $(xrandr | grep ' connected' | wc -l) == 3 ]] && xrandr --output eDP-1 --mode 1920x1080 --scale 0.9999x0.9999 --auto --rotate normal --pos 0x0 --output DP-1-2 --mode 2560x1440 --rate 75 --scale 0.9999x0.9999 --auto --rotate normal --pos 1920x0 --output DP-1-3 --mode 2560x1440 --scale 0.9999x0.9999 --auto --rotate normal --pos 4480x0"
  bash -c "[[ $(xrandr | grep ' connected' | wc -l) == 3 ]] && xrandr --output eDP-1 --off --output DP-1-2 --mode 2560x1440 --rate 75 --scale 0.9999x0.9999 --auto --rotate normal --pos 0x0 --output DP-1-3 --mode 2560x1440 --scale 0.9999x0.9999 --auto --rotate normal --pos 2560x0"

  bspc monitor eDP-1 -f

  # start redshift and caffine
  ~/.scripts/toggle_caffine.sh &
  ~/.scripts/toggle_redshift.sh &

  # start battery monitor
  ~/.scripts/battery.sh &
fi

xrandr --output eDP-1 --mode 1920x1080 --scale 0.9999x0.9999
~/.scripts/polybar.sh
~/.scripts/wallpaper.sh
~/.scripts/picom.sh &

# Set up custom keyboard mappings
test -f ~/.Xkeymap && xkbcomp ~/.Xkeymap $DISPLAY

# Disable scroll lock repeat for push to talk
xset -r 78

# Prevent the screen from automatically turning off (handled by lock.sh)
xset dpms 0 0 0
xset s off

# Trackpad tweaks
xinput set-prop "Elan TrackPoint" "libinput Accel Speed" 0.5
xmodmap ~/.Xmodmap

# xcape -e 'Mode_switch=Multi_key'
xcape -e 'Caps_Lock=Multi_key'

sxhkd &
