#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4


title=$(xtitle "$wid")
# notify-send "'$title' '$class' '$instance' '$consequences'"

case "$class" in
	Zathura)
		echo "state=tiled"
		;;
	"zoom ")
		case "$title" in
			Zoom|"Zoom Meeting"|"zoom ")
				eval "$consequences"
				if [ "$layer" == "above" ]; then
					echo "state=floating focus=off"
				else
					echo "state=tiled"
				fi
				;;
			*)
				echo "state=floating"
				;;
		esac
		;;
	*)
		case "$title" in
			Origin)
				echo "state=floating"
				;;
		esac
		;;
esac
