#!/usr/bin/env bash
icon=
pad_active="%{B#AC8476} %{B#AC8476} %{B#AC8476}"
pad_inactive="%{B#C4C7C5} %{B#C4C7C5} %{B#C4C7C5}"
last=""
show() {
    if [[ $last != $1 ]]
    then
        echo $1
        last=$1
    fi
}

while true
do
    if xrdb -query | grep -q "`cat ~/.config/polybar/caffine_on`"
    then
        show "$pad_active$icon$pad_active"
    else
        show "$pad_inactive$icon$pad_inactive"
    fi
    sleep 30 &
    echo ${!} > ~/.config/polybar/caffine.pid
    wait ${!} 2>/dev/null
done
