#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -theme ~/.config/rofi/powermenu.rasi <<< "> Lock|> Logout|> Suspend|> Reboot|> Windows|> Shutdown")"
            case "$MENU" in
                *Lock) ~/.scripts/lock_actual.sh ;;
                *Logout) bspc quit  ;;
								*Suspend) ~/.scripts/lock_actual.sh && systemctl suspend ;;
                *Reboot) systemctl reboot ;;
                *Windows) sudo /home/pantherman594/bin/refind_next_boot windows && systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
