#!/usr/bin/env bash
icon=
pad_active="%{B#E57C46} %{B#E57C46} %{B#E57C46}"
pad_inactive="%{B#C4C7C5} %{B#C4C7C5} %{B#C4C7C5}"
last=""
show() {
    if [[ $last != $1 ]]
    then
        echo $1
        last=$1
    fi
}

while true
do
    if pgrep -x "redshift" > /dev/null
    then
        show "$pad_active$icon$pad_active"
    else
        show "$pad_inactive$icon$pad_inactive"
    fi
    sleep 30 &
    echo ${!} > ~/.config/polybar/redshift.pid
    wait ${!} 2>/dev/null
done
